---
- hosts: all
  vars:
  tags:
    - tag1
  tasks:
    - ansible.builtin.copy:
        content: |
          i have executed!
          {{ injected_variable | default("var not injected") }}
          {{ content_from_a_var_file | default("var file not specified") }}
          {{ content_from_a_vault_file | default("vault file not specified") }}
        dest: "{{ test_filename }}"

- hosts: all
  vars:
  tags:
    - tag2
  tasks:
    - ansible.builtin.copy:
        content: |
          i have executed!
          {{ injected_variable | default("var not injected") }}
          {{ content_from_a_var_file | default("var file not specified") }}
          {{ content_from_a_vault_file | default("vault file not specified") }}
        dest: "{{ test_filename }}"

- hosts: this_group_exists
  tasks:
    - ansible.builtin.copy:
        content: |
          i have executed!
          {{ injected_variable | default("var not injected") }}
          {{ content_from_a_var_file | default("var file not specified") }}
          {{ content_from_a_vault_file | default("vault file not specified") }}
        dest: "{{ test_filename }}"


- hosts: all
  tags:
    - tag_never_specified
  tasks:
    - ansible.builtin.copy:
        content: "SHOULD NEVER EXECUTE: TAG NEVER SPECIFIED"
        dest: "{{ test_filename }}"

- hosts: idonotexist
  tasks:
    - ansible.builtin.copy:
        content: "SHOULD NEVER EXECUTE: HOST/GROUP NOT IN INVENTORY"
        dest: "{{ test_filename }}"
