---
- name: Make desired host reachable
  hosts: localhost
  connection: local
  tasks:
    - name: Add hostname "{{ hostname }}" to group "ansible_provision"
      ansible.builtin.add_host:
        name: "{{ hostname }}"
        groups: "ansible_provision"
      when: hostname != "localhost"
