---
# ++++++++++++++
# Now run some tasks on a desired host
# ++++++++++++++
- name: A test playbook running on a host "{{ hostname }}"
  hosts: "{{ hostname }}" # all
  tasks:
    - name: Create a file
      ansible.builtin.file:
        path: ~/test-play-file.txt
        state: touch
